// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CreateRegis(arg1) {
  return window['go']['repository']['Repository']['CreateRegis'](arg1);
}

export function CreateSKDP(arg1) {
  return window['go']['repository']['Repository']['CreateSKDP'](arg1);
}

export function DELETESKDP(arg1) {
  return window['go']['repository']['Repository']['DELETESKDP'](arg1);
}

export function GenerateNoRawat(arg1, arg2) {
  return window['go']['repository']['Repository']['GenerateNoRawat'](arg1, arg2);
}

export function GetKodePoliBPJS(arg1) {
  return window['go']['repository']['Repository']['GetKodePoliBPJS'](arg1);
}

export function GetLastNoRawat(arg1, arg2) {
  return window['go']['repository']['Repository']['GetLastNoRawat'](arg1, arg2);
}

export function GetListDockterBPJS(arg1) {
  return window['go']['repository']['Repository']['GetListDockterBPJS'](arg1);
}

export function GetListDokterKontrol(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['GetListDokterKontrol'](arg1, arg2, arg3);
}

export function GetListPoli(arg1) {
  return window['go']['repository']['Repository']['GetListPoli'](arg1);
}

export function GetMapPoli(arg1) {
  return window['go']['repository']['Repository']['GetMapPoli'](arg1);
}

export function GetMapingDokterDpjpvclaim(arg1) {
  return window['go']['repository']['Repository']['GetMapingDokterDpjpvclaim'](arg1);
}

export function GetPasienByNIK(arg1) {
  return window['go']['repository']['Repository']['GetPasienByNIK'](arg1);
}

export function GetPoliKontrolBPJS(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['GetPoliKontrolBPJS'](arg1, arg2, arg3);
}

export function ListHistory(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['ListHistory'](arg1, arg2, arg3);
}

export function ListSKDP(arg1, arg2) {
  return window['go']['repository']['Repository']['ListSKDP'](arg1, arg2);
}

export function SearchNoKartu(arg1, arg2) {
  return window['go']['repository']['Repository']['SearchNoKartu'](arg1, arg2);
}

export function SearchPasien(arg1, arg2) {
  return window['go']['repository']['Repository']['SearchPasien'](arg1, arg2);
}

export function SearchRujukanByNoKa(arg1, arg2) {
  return window['go']['repository']['Repository']['SearchRujukanByNoKa'](arg1, arg2);
}

export function SearchRujukanByNorujukan(arg1, arg2, arg3) {
  return window['go']['repository']['Repository']['SearchRujukanByNorujukan'](arg1, arg2, arg3);
}

export function Setup(arg1, arg2) {
  return window['go']['repository']['Repository']['Setup'](arg1, arg2);
}
